"""community reviews and expanded content

Revision ID: b1da8fb37ee0
Revises: e2b3cf774a0a
Create Date: 2026-04-27 01:59:41.553144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1da8fb37ee0'
down_revision = 'e2b3cf774a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_verification_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_token_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('mentor_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role_year', sa.String(length=120), nullable=False),
    sa.Column('pathway_tags', sa.JSON(), nullable=False),
    sa.Column('experience_tags', sa.JSON(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('contact_preference', sa.String(length=120), nullable=False),
    sa.Column('public_contact_text', sa.String(length=240), nullable=False),
    sa.Column('private_email', sa.String(length=255), nullable=False),
    sa.Column('email_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('mentorship_available', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_profile_email_hash'), ['email_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentor_profile_featured'), ['featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentor_profile_status'), ['status'], unique=False)

    op.create_table('question_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('topic', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('private_email', sa.String(length=255), nullable=False),
    sa.Column('email_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_submission_email_hash'), ['email_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_submission_status'), ['status'], unique=False)

    op.create_table('course_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('submitter_email_hash', sa.String(length=128), nullable=False),
    sa.Column('email_private', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('term_taken', sa.String(length=80), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('workload', sa.Integer(), nullable=False),
    sa.Column('usefulness', sa.Integer(), nullable=False),
    sa.Column('math_intensity', sa.Integer(), nullable=False),
    sa.Column('coding_intensity', sa.Integer(), nullable=False),
    sa.Column('memorization_intensity', sa.Integer(), nullable=False),
    sa.Column('would_take_again', sa.Boolean(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_review_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_review_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_review_submitter_email_hash'), ['submitter_email_hash'], unique=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_title', sa.String(length=180), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('units', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('source_urls', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
        batch_op.add_column(sa.Column('aliases', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
        batch_op.add_column(sa.Column('requirement_roles', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
        batch_op.add_column(sa.Column('track_tags', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
        batch_op.add_column(sa.Column('official_notes', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('student_reported', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('last_verified_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('source_confidence', sa.String(length=40), nullable=False, server_default='official-and-unofficial'))
        batch_op.add_column(sa.Column('last_verified_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('requirement_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_set', sa.String(length=80), nullable=False, server_default='level-ii-admission'))
        batch_op.add_column(sa.Column('units_required', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('option_units', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('track', sa.String(length=80), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_requirement_rule_requirement_set'), ['requirement_set'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_rule_requirement_set'))
        batch_op.drop_column('track')
        batch_op.drop_column('option_units')
        batch_op.drop_column('units_required')
        batch_op.drop_column('requirement_set')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('last_verified_at')
        batch_op.drop_column('source_confidence')
        batch_op.drop_column('body_html')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('last_verified_at')
        batch_op.drop_column('student_reported')
        batch_op.drop_column('official_notes')
        batch_op.drop_column('track_tags')
        batch_op.drop_column('requirement_roles')
        batch_op.drop_column('aliases')
        batch_op.drop_column('source_urls')
        batch_op.drop_column('units')
        batch_op.drop_column('level')
        batch_op.drop_column('official_title')

    with op.batch_alter_table('course_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_review_submitter_email_hash'))
        batch_op.drop_index(batch_op.f('ix_course_review_status'))
        batch_op.drop_index(batch_op.f('ix_course_review_course_id'))

    op.drop_table('course_review')
    with op.batch_alter_table('question_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_submission_status'))
        batch_op.drop_index(batch_op.f('ix_question_submission_email_hash'))

    op.drop_table('question_submission')
    with op.batch_alter_table('mentor_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_profile_status'))
        batch_op.drop_index(batch_op.f('ix_mentor_profile_featured'))
        batch_op.drop_index(batch_op.f('ix_mentor_profile_email_hash'))

    op.drop_table('mentor_profile')
    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_email_verification_token_email'))

    op.drop_table('email_verification_token')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
