"""initial schema

Revision ID: e2b3cf774a0a
Revises: 
Create Date: 2026-04-27 01:28:58.986153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b3cf774a0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('calendar_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('workload', sa.Integer(), nullable=False),
    sa.Column('math_intensity', sa.Integer(), nullable=False),
    sa.Column('coding_intensity', sa.Integer(), nullable=False),
    sa.Column('memorization_intensity', sa.Integer(), nullable=False),
    sa.Column('before_starting', sa.Text(), nullable=False),
    sa.Column('resources', sa.Text(), nullable=False),
    sa.Column('failure_points', sa.Text(), nullable=False),
    sa.Column('study_strategy', sa.Text(), nullable=False),
    sa.Column('unlocks', sa.Text(), nullable=False),
    sa.Column('pair_with', sa.Text(), nullable=False),
    sa.Column('student_tips', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_code'), ['code'], unique=True)

    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('source_links', sa.JSON(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_slug'), ['slug'], unique=True)

    op.create_table('requirement_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('course_options', sa.JSON(), nullable=False),
    sa.Column('rule_type', sa.String(length=40), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('advisory_note', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_rule_code'), ['code'], unique=True)

    op.create_table('resource_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_link')
    with op.batch_alter_table('requirement_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_rule_code'))

    op.drop_table('requirement_rule')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_slug'))

    op.drop_table('page')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_code'))

    op.drop_table('course')
    # ### end Alembic commands ###
